# Numpy 

Array is Collection of similar data type,used for store to secure

In [1]:
l=[6,'l']
type(l)

list

list is predefined but array is not that's why we used to import 

In [2]:
import array as arr

In [6]:
a=arr.array("i",[1,2,3,4])  #i=for integer
type(a)

array.array

In [7]:
print(a)

array('i', [1, 2, 3, 4])


In [8]:
a=arr.array("f",[1.2,2.45,3.7,4.62])
print(a)

array('f', [1.2000000476837158, 2.450000047683716, 3.700000047683716, 4.619999885559082])


In [20]:
a=arr.array("s",["Lbc","pqr","xyz"])
print(a)

ValueError: bad typecode (must be b, B, u, h, H, i, I, l, L, q, Q, f or d)

In [16]:
! pip install numpy

In [1]:
import numpy as np

In [23]:
#Numpy array creation
l=["a",2.3,4,5]
l

['a', 2.3, 4, 5]

In [24]:
type(l)

list

In [25]:
#convert list to Numpy array
arr1=np.array(l)
arr1

array(['a', '2.3', '4', '5'], dtype='<U32')

In [26]:
type(arr1)

numpy.ndarray

#in there we can store diff type data in list and then convert into array but there are not error becz of Numpy 
but this is not right way to write only we can check the work of numpy.

In [27]:
l1=[1,2,4,5]
l1

[1, 2, 4, 5]

In [28]:
type(l1)

list

In [29]:
arr2=np.array(l1)
arr2

array([1, 2, 4, 5])

In [30]:
type(arr2)

numpy.ndarray

In [31]:
#convert int to float
arr2.astype(float)

array([1., 2., 4., 5.])

In [5]:
import numpy as np
a=np.array([10,20,30])
np.repeat(a,5)   #repeat 5 times a array


array([10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30])

In [6]:
np.full(3,a)

array([10, 20, 30])

In [7]:
np.full(5,15)

array([15, 15, 15, 15, 15])

In [8]:
#repeat array of odd nums
ar1=np.arange(1,50) 

ar1[ar1%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [9]:
#repeat array of even nums
ar1=np.arange(1,50) 

ar1[ar1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [11]:
#genearte enenly spaced 4 no. between 10 to 20
np.linspace(10,22,33)

array([10.   , 10.375, 10.75 , 11.125, 11.5  , 11.875, 12.25 , 12.625,
       13.   , 13.375, 13.75 , 14.125, 14.5  , 14.875, 15.25 , 15.625,
       16.   , 16.375, 16.75 , 17.125, 17.5  , 17.875, 18.25 , 18.625,
       19.   , 19.375, 19.75 , 20.125, 20.5  , 20.875, 21.25 , 21.625,
       22.   ])

In [16]:
np.random.seed(0)          #for same random print in o/p every time run it can't change no. used seed ()
np.random.randint(0,26,8)   #any random no. 0 to 26

array([12, 15, 21,  0,  3,  3,  7,  9])

In [13]:
np.random.randint(20,22,8)

array([21, 21, 20, 20, 21, 20, 20, 20])

In [14]:
np.random.randint(0,500,10)

array([396, 314, 193, 486,  39,  87, 174,  88, 337, 165])

In [17]:
print(np.random.rand(2,3))

[[0.6235637  0.38438171 0.29753461]
 [0.05671298 0.27265629 0.47766512]]


In [18]:
print(np.random.randn(2,3))       #n for normal distribution range= -infinity to +infinity

[[-0.08767307  1.36687937  1.1253141 ]
 [-0.35899555  1.2206081  -1.33949555]]


In [19]:
print(np.random.randint(0,10))

print(np.random.randint(0,10,size=[2,3]))

0
[[3 5 0]
 [2 3 8]]


In [20]:
np.random.rand()

0.8009107519796442

In [22]:
np.random.normal()

0.22988653700036213

In [ ]:
-if we want to repeat same set of random no. every 

In [23]:
#create a random set
abc=np.random.RandomState(10)

print(abc.rand(2,2))   #2,2 for 2 rows and 2 cols

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]


In [6]:
import numpy as np
arr2=np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.sum(arr2)

45

In [11]:
arr2.sum()

45

In [12]:
np.cumsum(arr2)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [13]:
np.max(arr2)  #find max in no. in that array

9

In [14]:
np.min(arr2)

1

In [21]:
arr2.min()

1

In [15]:
np.argmax(arr2)

8

In [16]:
np.argmin(arr2)

0

In [17]:
np.mean(arr2)

5.0

In [19]:
np.median(arr2)

5.0

In [22]:
np.var(arr2)  #var=variance

6.666666666666667

In [23]:
np.std(arr2)  #standard deviation ...squar root 

2.581988897471611

In [24]:
print(arr2)
np.percentile(arr2,90)

[1 2 3 4 5 6 7 8 9]


8.2

In [27]:
np.percentile(arr2,[10,70])

array([1.8, 6.6])

# #Multidimentional array

In [32]:
l1=[1,2,3,5]           
l2=[4,5,6,7]
l3=[6,7,8,9]
A=np.array([[[l1,l2,l3]]])
print(A)

print(A.ndim)    #find dimention of array...on opening and closing [] braces 

[[[[1 2 3 5]
   [4 5 6 7]
   [6 7 8 9]]]]
4


In [39]:
#operation pn 2D array
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,1,13],[14,15,16,3]])
print(A)


print(np.min(A,axis=0))  #min value in columns..used 0
print(np.min(A,axis=1))  #min value in rows..used 1
print(np.max(A,axis=0))
print(np.max(A,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1 13]
 [14 15 16  3]]
[1 2 1 3]
[1 5 1 3]
[14 15 16 13]
[ 4  8 13 16]


In [43]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  1, 13],
       [14, 15, 16,  3]])

In [45]:
print(A.size)
A.shape

16


(4, 4)

# Stastical operations

In [40]:
#sum of all no. in 2D array
A.sum()

117

In [41]:
A.max()

16

In [42]:
A.min()

1

# Operations on Array

In [5]:
import numpy as np


In [6]:
a=np.array([10,20,30])
b=a.copy()

In [7]:
b

array([10, 20, 30])

In [8]:
b.sort()

In [9]:
#Reshape
l1=[1,2,3,5]           
l2=[4,5,6,7]
l3=[6,7,8,9]
A=np.array([[[l1,l2,l3]]])
print(A)

[[[[1 2 3 5]
   [4 5 6 7]
   [6 7 8 9]]]]


In [19]:
A1=np.array([1,2,3,6,7,8,9])

print(A1)

print(" ")

print(A1.reshape[2,3])
print(A1)


[1 2 3 6 7 8 9]
 


TypeError: 'builtin_function_or_method' object is not subscriptable

In [23]:
#indexing

arr1=np.array([1,2,3,4,5]) #for finding particular element in array
print(arr1[4])
print(arr1[-3])
print(arr1(-1))

5
3


TypeError: 'numpy.ndarray' object is not callable

In [25]:
#Concatenation:

arr1=np.array([[1,2,3,4],[98,784,5,55]])
arr2=np.array([[1,2,3,4],[98,784,5,55]])
print(np.concatenate((arr1,arr2),axis=1))
print("\n")


[[  1   2   3   4   1   2   3   4]
 [ 98 784   5  55  98 784   5  55]]




In [29]:
#slicing
arr1[::-1]

array([[ 98, 784,   5,  55],
       [  1,   2,   3,   4]])

In [27]:
arr1

array([[  1,   2,   3,   4],
       [ 98, 784,   5,  55]])

In [32]:
print(arr1[1:3])
print(arr1[1:3,3:])
print(arr1[:,1:])
print(arr1[1:3,1:4])
print(arr1[1:2,1:3])

[[ 98 784   5  55]]
[[55]]
[[  2   3   4]
 [784   5  55]]
[[784   5  55]]
[[784   5]]
